version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge


#RabbitConfig__ConsumerQueue=billing.monitor-consumer
#RabbitConfig__DeadLetterExchangeQueue=billing.monitor-dead-letter-exchange
#RabbitConfig__MonitorBatchExchangeQueue=billing.monitor-batch-exchange
#RabbitConfig__ConsumerExchangeQueue=billing.monitor-consumer-exchange
#RabbitConfig__TimeToLiveInMilisseconds=5000
#Logging__LogLevel__Default=Information

#docker run --rm --env-file=file <docker-image>